config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[index show edit update]

  get 'new_match', to: 'matches#new_match', as: :new_match
  get 'no_match', to: 'matches#no_match', as: :no_match

  resources :categories, only: [:index] do
    resources :hobbies, only: %i[index show]
  end
  resources :matches, except: :edit do
    resources :messages, only: %i[create]
  end

  resources :user_hobbies, only: %i[create new destroy] do
    collection do
      post "create_many"
    end
  end

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :user_hobbies
  has_many :hobbies, through: :user_hobbies
  has_many :sent_matches, foreign_key: "sender_id", class_name: "Match"
  has_many :received_matches, foreign_key: "receiver_id", class_name: "Match"

  def all_matches
    Match.where("sender_id = :id OR receiver_id = :id", id: self.id)
  end

  def next_match_user
    # Missing check if I already sent a match
    users_with_same_hobbies = User.joins(:user_hobbies).where("user_hobbies.hobby_id IN (?)", self.hobby_ids)

    users_already_sent_a_match = sent_matches.pluck(:receiver_id)

    users_already_received_a_match = received_matches.where(status: [:accepted, :rejected]).pluck(:sender_id)

    User.where.not(id: id)
        .where(id: users_with_same_hobbies.pluck(:id))
        .where.not(id: users_already_sent_a_match)
        .where.not(id: users_already_received_a_match)
        .first

    #User.joins(:user_hobbies).joins("LEFT JOIN matches ON users.id = matches.sender_id OR users.id = matches.receiver_id")
    #    .where.not(id: self.id)
    #    .where("user_hobbies.hobby_id IN (?)", self.hobby_ids)
    #    .where.not(matches: { id: self.sent_matches.pluck(:id) })
    #    .where.not(matches: { id: self.received_matches.where.not("status = 0").pluck(:id) })
    #    .first
  end

  def new_accepted_matches
    self.all_matches.where(status: "accepted")
        .left_joins(:messages)
        .where("messages.id IS NULL")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :match]

  def index
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def show
    @userhobbies = current_user.user_hobbies
    @categories = Category.all
    if params[:categories]
      ids = params[:categories].keys.select do |id|
        params[:categories][id] == "1"
      end
      @categories = Category.where(id: ids)
    end

    if params[:address]
      current_user.address = params[:address]
      current_user.save
    end

    if current_user.address.blank?
      redirect_to root_path, alert: "Please enter a location to continue"
    end
  end

  #def next_match
  #  @user = User.find(params[:id])
  #  @user_hobby = UserHobby.where(user_id: params[:id])
  #  @match = current_user.all_matches.find_by("sender_id = ? OR receiver_id = ?", @user.id)
  #  @match ||= Match.new
  #end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo)
  end

  def set_user
    @user = User.find(params[:id])
    authorize(@user)
  end
end

app/views/users/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-lg-6">
    <div class="container-form-ext">
      <div class="row justify-content-md-center">
        <div class="col col-md-8 col-lg-10">
          <div class="container-form-int col-10 offset-1">
            <%= simple_form_for [@user] do |f|   %>
              <%= f.input :first_name , label: 'Your first name'%>
              <%= f.input :last_name , label: 'Your last name'%>
              <%= f.input :photo, as: :file %>
              <%= f.button :submit, "Submit", class: "btn-add-hobby edit-user-button"  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="user-banner">
        <% if @user.photo.key.nil?%>
          <p>you dont have a photo</p>
        <% else%>
          <div class="profile-image" style="background-image: url('<%= cl_image_path @user.photo.key %>')"></div>
        <% end%>
        <div class="d-flex flex-wrap justify-content-center align-items-center mt-2">
          <h1 class="px-2"><%= @user.first_name %>'s Profile Page</h1>
          <%= link_to edit_user_path(@user) do %>
          <i class="fas fa-edit" style="color:white"></i>
          <% end %>
        </div>
      <h2 class="m-0 mt-2">Your hobbies</h2>
      </div>
    </div>
  </div>
</div>
<div class="d-flex flex-wrap justify-content-around m-0 mx-4">
  <% @userhobbies.each do |userhobby| %>
    <div class="hobbie-delete mt-3 p-2 d-flex align-items-center ">
      <div class="btn-delete"><%=link_to image_tag("icon-delete.png"), userhobby, method: :delete, data: { confirm: "Are you sure you want to delete your hobby?" } %>
      </div>
      <h3 class="m-0 py-1 px-2 m-0" style="color: white"><%= userhobby.hobby[:name] %></h2>
    </div>
  <% end %>
</div>
<div class="homepage-all">
  <div id="homepage-block">
    <div>
      <h3 class="homepage-tagline m-0 mb-3 ">Change your hobbies</h3>
    </div>
  <%= form_with url: categories_path, method: :get do |f| %>
      <div data-controller="geocoder" data-geocoder-api-key-value="<%=ENV['MAPBOX_API_KEY']%>">
        <%= f.text_field :address,
                          data: { geocoder_target: "address" },
                          :class => "searchbar-homepage d-none"%>
      </div>
      <p class="form-subtitle">Select categories you're interested in</p>
      <div class="container">
          <% @categories.each_slice(2) do |category_pair| %>
            <div class="row shifted-row">
              <% category_pair.each do |category| %>
                <div class="col-6">
                  <%= f.check_box "categories[#{category.id}]", :class => "tag-selector" %>
                  <%= f.label "categories[#{category.id}]", category.name %>
                </div>
              <% end %>
            </div>
          <% end %>
      <div class="tag-item-inputs">
          <%= f.submit 'Next', :class => "searchbar-submit" %>
        <% end %>
    </div>
  </div>
</div>