config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[index show edit update]

  get 'new_match', to: 'matches#new_match', as: :new_match
  get 'no_match', to: 'matches#no_match', as: :no_match

  resources :categories, only: [:index] do
    resources :hobbies, only: %i[index show]
  end
  resources :matches, except: :edit do
    resources :messages, only: %i[create]
  end

  resources :user_hobbies, only: %i[create new destroy] do
    collection do
      post "create_many"
    end
  end

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
end

app/views/shared/_favicon.html.erb
<%= favicon_link_tag 'logo-white.png' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid navbar-main">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-white" %>
    <% end %>

    <h2><%= link_to 'Hobbymate', root_path, class: "navbar-title-website" %></h2>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to matches_path, class: "nav-link message" do %>
              <%= image_tag "message" %>
              <%= render 'shared/notifications_match' %>
            <% end %>
            </li>
            <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link message" do %>
              <%= image_tag "profile" %>
            <% end %>
            </li>
            <li class="nav-item">
            <%= link_to destroy_user_session_path, :method => :delete , class: "nav-link message" do %>
              <%= image_tag "logout" %>
            <% end %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link message-login" do %>

            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notifications_match.html.erb
<% if current_user.new_accepted_matches.present? %>
  <a class="notification" onclick="toastr.error('You have a match');">
    <%= current_user.new_accepted_matches.count() %>
  </a>
<% end %>

app/views/shared/_notifications_message.html.erb
<a class="btn btn-danger" onclick="toastr.error('You have a message');"><%= Message.user.count() %></a>