config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[index show edit update]

  get 'new_match', to: 'matches#new_match', as: :new_match
  get 'no_match', to: 'matches#no_match', as: :no_match

  resources :categories, only: [:index] do
    resources :hobbies, only: %i[index show]
  end
  resources :matches, except: :edit do
    resources :messages, only: %i[create]
  end

  resources :user_hobbies, only: %i[create new destroy] do
    collection do
      post "create_many"
    end
  end

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :messages, dependent: :destroy

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:destroy, :update, :show]
  before_action :my_matches, only: :index

  def index
    @accepted_matches = []
    my_matches.each do |match|
      unless match.nil?
        @accepted_matches << match
      end
    end
    @markers = @accepted_matches.map do |match|
      if match.present?
        {
          lat: match.latitude,
          lng: match.longitude,
          info_window: render_to_string(partial: "info_window", locals: { match: match }),
          image_url: helpers.image_url(match.photo.url)
        }
      end
    end
  end

  def show
    @messages = @match.messages
    @message = Message.new
  end

  def destroy
  end

  def new
    @match = Match.new
    authorize(@match)
  end

  def create
    @match = Match.new(match_params)
    @match.sender_id = current_user.id
    authorize(@match)
    @match.save
    redirect_to new_match_path(status: @match.status, old_match_id: @match.id)
  end

  def update
    @match.update(match_params)
    redirect_to new_match_path(status: @match.status, old_match_id: @match.id)
  end

  def new_match
    if params[:old_match_id]
      @old_match = Match.find(params[:old_match_id])
    end
    @user = current_user.next_match_user
    if @user.nil?
      redirect_to no_match_path
      authorize(Match.new)
    else
      @user_hobby = UserHobby.where(user_id: @user.id)
      @match = current_user.all_matches.find_by("sender_id = ? OR receiver_id = ?", @user.id, @user.id)
      @match ||= Match.new
      authorize(@match)
    end
  end

  def no_match
  end

  private

  def match_params
    params.require(:match).permit(:receiver_id, :status)
  end

  def set_match
    @match = Match.find(params[:id])
    authorize(@match)
  end

  def my_matches
    @matches = Match.where(sender_id: current_user.id).or(Match.where(receiver_id: current_user.id))
    @my_matches = @matches.map do |match|
      if match.status == "accepted"
        if match.sender_id == current_user.id
          user = match.receiver_id
        else
          user = match.sender_id
        end
        User.find(user)
      end
    end

  end
end

app/views/matches/_info_window.html.erb
<div class="d-flex justify-content-start align-items-center mb-2">
<div class="map-info-avatar" style="background-image: url('<%= cl_image_path match.photo.key %>')"></div>
<h2 class= "m-0" style="color:black" ><%= match.first_name %> <%= match.last_name %></h2>
</div>
<p class= "m-0 mb-0"><%= match.address %></p>

app/views/matches/index.html.erb
<div class="match-container">
  <h1 class="matches-index-title">Your matches</h1>
  <div class="match-page-page">
    <div class="match-page">
      <% @matches.each do |match| %>
        <div class="match-chat">
          <% if match.status == "accepted" %>
            <% if match.sender_id == current_user.id %>
              <div class="match-avatar m-0"><%= cl_image_tag User.find(match.receiver_id).photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %></div>
              <%= link_to match_path(match, anchor: "message-#{match&.messages&.last&.id}") do %>
              <p class="match-bubbles">Chat to <%= User.find(match.receiver_id).first_name %> <%= User.find(match.receiver_id).last_name %></p>
              <% end %>
            <% else %>
              <div class="match-avatar m-0"><%= cl_image_tag User.find(match.sender_id).photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %></div>
              <%= link_to match_path(match, anchor: "message-#{match&.messages&.last&.id}") do %>
              <p class="match-bubbles">Chat to <%= User.find(match.sender_id).first_name %> <%= User.find(match.sender_id).last_name %></p>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="m-auto mb-2" style="width: 90vw; height: 30vh; margin: 0em 1em 0em 1em"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/matches/new_match.html.erb
<div class="swipe-container" data-controller="swipe">
  <h3 class="swipe-title" style="color: white">Swipe for your next hobbymate</h3>

      <div class="row justify-content-center h-100">
        <div class="col">
          <div class="user-card" data-swipe-target="card">
            <div class="user-card-image" style="background-image: url(<%= cl_image_path(@user.photo.key) %>)"></div>
              <div class="card-name">
                <div>
                  <h2 class="m-0"><%= @user.first_name %>, <%= @user.age %></h2>
                  <div class="tags-hobby scolled">
                    <% @user_hobby.each do |user_hobby| %>
                      <div class="tag-hobby"><p> <%=user_hobby.hobby.name%></p></div>
                    <% end %>
                  </div>
                  <p class="swipe-text scolled"><%= @user.bio %></p>
                </div>
                <div class="buttons-swipe">
                  <% if @match.status == "pending"%>
                    <%= simple_form_for @match do |f|  %>
                      <%= f.input :status, input_html: { value: "rejected" }, as: :hidden  %>
                      <%= f.submit "Pass", class: "btn btn-match-pass", data: {swipe_target:"reject"}%>
                    <% end %>
                    <%= simple_form_for @match do |f| %>
                      <%= f.input :status, input_html: { value: "accepted" }, as: :hidden  %>
                      <%= f.submit "Accept", class: "btn btn-match", data: {swipe_target:"accept"}%>
                    <% end %>
                  <% else %>
                    <%= simple_form_for @match do |f| %>
                      <%= f.input :receiver_id, input_html: { value: @user.id }, as: :hidden  %>
                      <%= f.input :status, input_html: { value: "rejected" }, as: :hidden  %>
                      <%= f.submit "Pass", class: "btn btn-match-pass", data: {swipe_target:"reject"}%>
                    <% end %>
                    <%= simple_form_for @match do |f| %>
                    <%= f.input :receiver_id, input_html: { value: @user.id }, as: :hidden  %>
                      <%= f.input :status, input_html: { value: "pending"}, as: :hidden  %>
                      <%= f.submit "Accept", class: "btn btn-match", data: {swipe_target:"accept"} %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% if params[:status] == "accepted" %>
    <div class="modal p-0" id="match_modal" data-controller="match-modal" tabindex="-1" >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="text-align-center pt-3">
            <h2 class="modal-title"> It's a Match! </h2>
          </div>
          <div class="modal-body">
            <h5 id="modal-h2">You matched with <%= @old_match.sender.first_name %> <%= @old_match.sender.last_name %></h5>
            <div class="modal-match-body d-flex justify-content-around align-items-center">
              <div class="modal-image" style="background-image: url('<%= cl_image_path current_user.photo.key %>')"></div>
              <i class="fas fa-star" id="modal-star"></i>
              <div class="modal-image" style="background-image: url('<%= cl_image_path @old_match.sender.photo.key %>')"></div>
            </div>
          </div>
          <div class="modal-footer pt-0 pb-3">
            <button type="button" class="btn modal-button" data-bs-dismiss="modal">Keep looking</button>
            <%= link_to "Start chat", match_path("#{@old_match.id}#message-"), class: 'btn modal-button' %>

          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/matches/no_match.html.erb
<%# <body class="flex-column center-center">
    <header>Swipe Left or Right</header>
    <div class="square center-center"></div>
</body>   %>
<div class="no_match_page col-12">
  <div class="show_match position-relative col-12">
    <div class="container">
      <div class="container cercle d-flex align-items-center">
        <div class="profile-picture">
          <% if current_user.photo.key.nil?%>
            <p>you dont have a photo</p>
          <% else%>
            <div class="profile-image" style="background-image: url('<%= cl_image_path current_user.photo.key %>')"></div>
          <% end%>
        </div>
        <svg class="loader" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 360">
          <%# <circle cx="180" cy="180" r="180" stroke="#874356"/> %>
          <circle cx="180" cy="180" r="167" stroke="#B762C1" stroke-opacity="30%"/>
          <circle cx="180" cy="180" r="142" stroke="#B762C1" stroke-opacity="65%"/>
          <circle cx="180" cy="180" r="117" stroke="#B762C1" style="100%"/>
        </svg>
      </div>
    </div>
  </div>
  <div class="show_match col-12">
    <div class="d-flex flex-wrap justify-content-around align-items-center mt-2">
      <h1>There's no one new around you</h1>
    </div>
  </div>
  <div class="show_match col-12">
    <div class="btn-show_match">
      <p><%= link_to 'Show my matches', matches_path %></p>
    </div>
  </div>
</div>

app/views/matches/show.html.erb
<div class="container match"
  data-controller="match-subscription"
  data-match-subscription-match-id-value="<%= @match.id %>"
  data-match-subscription-current-user-id-value="<%= current_user.id %>"
>
  <h1 class="messages-main-title">Your conversation with <%= @match.sender_id == current_user ? "#{User.find(@match.receiver_id).first_name}" : "#{User.find(@match.sender_id).first_name}" %></h1>
  <%= render "messages/index" %>
</div>