config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: %i[index show edit update]

  get 'new_match', to: 'matches#new_match', as: :new_match
  get 'no_match', to: 'matches#no_match', as: :no_match

  resources :categories, only: [:index] do
    resources :hobbies, only: %i[index show]
  end
  resources :matches, except: :edit do
    resources :messages, only: %i[create]
  end

  resources :user_hobbies, only: %i[create new destroy] do
    collection do
      post "create_many"
    end
  end

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_hobbies
  has_many :hobbies, through: :category_hobbies

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all
    if params[:categories]
      ids = params[:categories].keys.select do |id|
        params[:categories][id] == "1"
      end
      @categories = Category.where(id: ids)
    end

    if params[:address].present?
      current_user.address = params[:address]
      if current_user.save
        redirect_to categories_path(categories: params[:categories].permit!)
      end
    end

    if current_user.address.blank?
      redirect_to root_path, alert: "Please enter a location to continue"
    end
  end

  def show
  end

  private

  def set_category
    @category = Category.find(params[:hobby_id])
    authorize(@category)
  end
end

app/views/categories/_carousel_controls.html.erb
<button class="carousel-control-prev" type="button" data-bs-target="#category-carousel-<%= category.id %>" data-bs-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#category-carousel-<%= category.id %>" data-bs-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Next</span>
</button>

app/views/categories/_hobby_card.html.erb
<div class="hobby-card">
  <div class="card-image">
    <%= cl_image_tag hobby.photo.key  %>
  </div>
  <div class="hobby-items-div">
    <div class="card-name">
      <%= hobby.name %>
    </div>
    <%= f.check_box "hobbies[#{hobby.id}]", :class => "add-hobby" %>
    <%= f.label "hobbies[#{hobby.id}]", "Add hobby" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <%= form_with url: create_many_user_hobbies_path, method: :POST do |f| %>
        <% @categories.each do |category| %>
            <div class="cards-category">
              <h1 class="text-center pt-3"><%= category.name %></h1>
                <div class="category-hobbies">
                  <div id="category-carousel-<%= category.id %>" class="carousel slide" data-bs-interval="false" data-bs-ride="carousel">
                    <div class="carousel-inner">
                      <% category.hobbies.each_slice(2).with_index do |hobby_pair, index| %>
                        <div class="carousel-item <%= "active" if index == 0  %>">
                          <div class="d-flex flex-row justify-content-center">
                            <% hobby_pair.each do |hobby|  %>
                              <div class="px-3">
                                <%= render "hobby_card", hobby: hobby, f: f %>
                              </div>
                            <% end  %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                    <%= render "carousel_controls", category: category %>
                  </div>
                </div>
            </div>
        <% end %>
      <div class="tag-item-inputs">
        <%= f.submit 'Next', :class => "searchbar-submit" %>
      </div>
      <% end %>
    </div>
  </div>
</div>